services:
  postgres:
    container_name: postgres-sql-lingua
    image: postgres
    environment:
      POSTGRES_PASSWORD: lingua123456
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: lingua_hub
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - spring-demo

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres: